version: '3.3'

services:
  postgres:
    container_name: dps_postgres
    image: postgres:13.3
    restart: always
    hostname: postgres
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_HOST: '${POSTGRES_HOST}'
      POSTGRES_PORT: '${POSTGRES_PORT}'
      CONFIGS: "listen_addresses:'*',max_replication_slots:5"
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
    healthcheck:
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: dps_backend
    restart: always
    build: ./project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8000:8000
    env_file: project/.env
    environment:
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres

  celery:
    container_name: dps_celery
    image: celery:4.0.2
    restart: always
    build: .
    command: celery -A django_project worker -Q low,default,high --loglevel=info
    env_file: .env
    volumes:
      - ./project:/usr/src/app
    depends_on:
      - backend
      - postgres
      - redis

  redis:
    container_name: dps_redis
    image: redis:5-alpine
    restart: always
    command: redis-server
    ports:
      - '6379:6379'